site_name: ""

theme:
  name: material
  custom_dir: overrides
  favicon: images/payrange-logo.png
  logo: images/payrange-logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.integrate
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Machine Library:
      - Speed Queen & Alliance: speed-queen.md
      - Maytag & Whirlpool: maytag.md
      - LG Commercial: lg-commercial.md
      - Dexter: dexter.md
      - Continental: continental.md
      - IPSO: ipso.md
      - Wascomat & Laundrylux: wascomat.md
  - "Mobile App Resources": mobile-app-resources.md
  - Manage Training: manage-training.md
  - Troubleshooting: troubleshooting.md
  - Questions & Feedback: questions-feedback.md
  - Community Forum:
      - Discussion Board: forum.md
      - Live Installer Chat: chat.md

extra_css:
  - stylesheets/extra.css

copyright: "© 2026 PayRange LLC. | Patents: www.payrange.com/patents"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

use_directory_urls: false

extra:
  announcement: "Community Forum Coming Soon!"